---
# =========================================================
# Setup variables and directories
# =========================================================

- name: Creating build directories for each host
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - set_fact:
        build_dir: "{{ build_dir }}/{{ inventory_hostname }}/tmp"
        junos_conf: "{{ build_dir }}/{{ inventory_hostname}}/junos.conf"
    - name: remove host build temp directory
      file: path={{ build_dir }} state=absent
    - name: create host build temp directory
      file: path={{ build_dir }} state=directory
#    - name: group by firewall role
#      group_by: key=fw_role_{{ FW_role }}

# =========================================================
# Role based config template building
# =========================================================

- name: Build base system for Junos devices
  hosts: junos
  connection: local
  gather_facts: no
  roles:
    - base_system

#- name: Template-build PCI Firewalls
#  hosts: fw_role_PCI
#  connection: local
#  gather_facts: no
#  roles:
#    - ansible_user
#    - fw_baseconf
#    - fw_pciconf

#- name: Template-build DMZ Firewalls
#  hosts: fw_role_DMZ
#  connection: local
#  gather_facts: no
#  roles:
#    - ansible_user
#    - fw_baseconf
#    - fw_dmzconf

# =========================================================
# Finish by assembling config snippets into single file
# =========================================================

- name: Creating final junos.conf
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: assembling configfurations
      assemble: src={{ build_dir }} dest={{ junos_conf }}