---
platform: qfabric

my_host_name:
    qf1

my_domain_name:
    lab

local_timezone:
    America/New_York

syslog_prefix:
    QF1

node_group:
    - name: NONE
      devices:
        - sn: 1c1c1c1c
          alias: IC-0
        - sn: 2c2c2c2c
          alias: IC-1
    - name: NW-NG-0
      devices:
        - sn: 99999990
          alias: NODE-9A
        - sn: 99999991
          alias: NODE-9B
    - name: NODE-1
      devices:
        - sn: 11111111
          alias: NODE-1A
    - name: NODE-2
      devices:
        - sn: 22222222
          alias: NODE-2A
        - sn: 22222223
          alias: NODE-2B

inter_ranges:
#    - name: TV3-Interfaces
#      start_int: TV3-A:xe-0/0/0
#      end_int: TV3-A:xe-0/0/47
#      vlan: 
#          24-PIQ
#      tagged: FALSE

#    - name: CV1-Interfaces
#      start_int: CV1-A:xe-0/0/0
#      end_int: TV3-A:xe-0/0/47
#      vlan: 
#          Hadoop
#      tagged: TRUE

    - name: CV2-Interfaces
      members:
        - { start_int: 'CV2-A:xe-0/0/0', end_int: 'CV2-A:xe-0/0/47' }
        - { start_int: 'CV2-B:xe-0/0/0', end_int: 'CV2-B:xe-0/0/47' }
      vlan: 24-PIQ
      tagged: TRUE
      vlan:
        24-PIQ
        Hadoop

vlans:
     - name: 24-PIQ
       vlan_id: 24
       description: "Native VLAN for SAN-A"
       l3_intr: TRUE
     - name: Hadoop 
       vlan_id: 10
       description: "Hadoop Front End"
       l3_intr: FALSE

link_agg:
     - description: "Parse from LLDP"
       nodes:
        - alias: DCM1-A
        - alias: DCM2-A
        - port: xe-0/0/2 

native_vlan: 2 
      
